### ISSUE TITLE
Rearranging roles

### ISSUE THREAD

**Issue by luked297** [camdram/camdram#372] opened 2017-02-19 00:39 UTC
No matter how many times I try to re-arrange cast or production team roles on a show's camdram page the order saves temporarily, but they always seem to shuffle around the next day, which is really not ideal. Is someone able to fix this bug?

**Comment by CHTJonas** [comment] 2018-06-14 13:35
@luked297 are you still experiencing this bug? I am currently unable to reproduce. It's been a while since you opened this issue so if things are working now are you happy for me to mark this as closed?

**Comment by CHTJonas** [comment] 2018-06-17 23:35
I have been unable to reproduce this after trying several times so I am closing. @luked297 please reopen if you experience the same issue again in the future.

**Comment by GKFX** [comment] 2018-07-20 18:33
Reproduced by @tc467 on #444.

**Comment by hoyes** [comment] 2018-07-21 12:43
Can't reproduce now... possibilities I can think of:
 * It's caused by adding/deleting roles in a specific order, which cause the 'order' fields to be temporarily invalid in some way.
 * More than one person is mutating the order at the same time(!)
 * The session timed out. IIRC the re-order server callback doesn't report any errors so if the re-order actually failed the UI stays reordered (until a page refresh) without any error feedback.

The stuff discussed in #323 implicates redoing/rethinking most of this anyway so diminishing returns spending too much time looking into it.

**Comment by GKFX** [comment] 2018-09-05 14:53
Sentry issue: [CAMDRAM-WEB-2](https://sentry.io/camdram-webteam/camdram-web/issues/675759164/)

**Comment by GKFX** [comment] 2018-11-10 22:41
Potentially relevant is that until one of my styling changes it was possible to rearrange roles when not fully authenticated (as the JS was still being loaded), but of course this shouldn’t have taken effect at the backend as the user wasn’t fully authenticated. This isn’t *quite* what Luke thinks he saw but maybe it’s what actually happened.

**Comment by CHTJonas** [comment] 2018-11-11 19:32
Can't recall if this has been discussed elsewhere, but I think that show admins probably ought to need to press a UI button to enter a 'role edit mode'. In said mode they'd be able to add/remove/reorder any roles. Currently we're combining the view and edit actions for roles and that feels a tiny bit un-RESTful.

**Comment by CHTJonas** [comment] 2019-01-10 09:35
Possibly relevant support ticket: https://support.camdram.net/tickets/1349

**Closed** 2019-12-24 20:12 UTC
Labels: bug, irreproducible
