### ISSUE TITLE
Date/time picker not supported in Safari

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#472] opened 2018-08-08 15:05 UTC
The old javascript date/time picker that allowed you to select Start Date/End Date/Time for new shows no longer works.

**Comment by hoyes** [comment] 2018-08-08 16:01
Which browser/OS? I think I removed the JS datepicker stuff when doing #397 on the assumption that it's redundant now that <input type="date"/> etc works in all browsers. But I may well be missing something...

**Comment by CHTJonas** [comment] 2018-08-08 17:41
Oh ok yeah I see what you mean. It works in Firefox just not in Safari 11.1.2/macOS 10.13.6 (High Sierra) - weird.

**Comment by hoyes** [comment] 2018-08-08 17:53
Damn you Safari: https://caniuse.com/#feat=input-datetime Curious that it is supported on iOS. Looks like I was wrong about "all browser"... 

Our audience is apparently 7.3% Safari (compared to 1.68% UK-wide in the link above!) plus 2% using IE which doesn't support it either. Hopefully someone somewhere's made a polyfill.

**Comment by CHTJonas** [comment] 2018-08-08 18:13
Yeah that's annoying it looks like a really nice way of doing things as well without the JS bloat. Coming on for 10% is a reasonable amount though. I guess we can either revert that single part of the commit or try and find a polyfill?

**Comment by hoyes** [comment] 2018-08-08 18:18
Yea agree we need to do something about it.

Probably equal effort to put the back the old solution (which used JQueryUI) or find some other polyfill at this point. Each JS dependency required individual faffing when porting to Webpack anyway and I (incorrectly) thought we could get away without porting jQueryUI.

**Comment by GKFX** [comment] 2018-08-08 18:42
FWIW I’m on Chrome on Linux and I don’t particularly like the date and time pickers. Dates for me are requested in US format; a brief skim through StackOverflow suggests that that’s somehow something I as a user could fix; no idea how though! Also the time picker isn’t very friendly: it’s 12 hr and requires you to type the AM/PM manually even after saying e.g. 19:45. I’ve had to hold up one show approval because of 12hr/24hr confusion.

So yeah I’d suggest something like jQuery UI if it’s achievable and gives better results.

**Comment by GKFX** [comment] 2018-08-08 18:53
Or something like this, which definitely needs new CSS (at least!), but doesn't need a framework. Since it's unlikely to be updated we can just tweak it a bit and dump it in our assets directory. https://github.com/chrishulbert/datepicker.

**Comment by GKFX** [comment] 2018-08-08 19:01
A by-platform approach might be for the best though (even though browser-sniffing is frowned upon). iOS's date picker is excellent. I don't have a modern Android device to hand, but if Android is good as well, we could say that mobile users get input[type=date], and desktop users get a bit of JS. (In terms of actual implementation, I guess we'd serve input[type=date], and then change date to text if we decided the platform didn't have a good native date picker.)

**Comment by hoyes** [comment] 2018-08-08 19:27
Yea Android uses the OS date/time pickers too which are decent.

I worry a little that platform-specific overrides are liable to break over time and are difficult to test comprehensively. E.g. It probably ought to exclude Chrome on Android, and it's maybe worth investigating if Chrome on Windows/Mac looks any different. The former JS datepicker was only injected after detecting an explicit lack of date input support - I guess it could be augmented to include some carefully selected User Agent strings too...

There are apparently some custom CSS selectors than can be used to change the datepicker colours in Chrome which we could maybe try first.... http://qnimate.com/guide-to-styling-html5-input-elements/

Chrome on my Linux is d/m/y and 24 hour so I'm guessing there's some locale setting somewhere (no idea where either). I'd argue (maybe controversially) that respecting the system locale isn't a bug though, and the difficulty in setting this correctly probably doesn't apply on Windows/Mac.

**Comment by hoyes** [comment] 2018-08-08 19:37
https://github.com/chemerisuk/better-dateinput-polyfill has slightly less objectionable default styling and even has a "data-polyfill=desktop" option to make it always active on Desktops (so maybe desktop-detection isn't as hard as I thought).

**Comment by hoyes** [comment] 2018-08-18 17:58
I ended up going back to jQueryUI in the end because it turns out it was actually still included (the slider thing on the homepage uses ui.draggable) and it was the only thing that didn't clash with foundation CSS. I stole the `"orientation" in window` kludge from the better-dateinput-polyfill thing above though so it's only active on desktops

**Comment by GKFX** [comment] 2018-08-18 21:06
Close but not quite: it's still input[type=date] on desktop so there are two calendar pop-ups. (FF/Linux).
![screenshot-izmnn](https://user-images.githubusercontent.com/5357642/44303211-9b0fdb00-a332-11e8-8e10-98f4f4a104f2.png)
If jQueryUI doesn't let you get rid of the type then hiding jQuery's calendar would also work, as it's better to have zero or one calendar than one or two.

**Comment by hoyes** [comment] 2018-08-18 21:51
[Long sigh...]

I changed the datepicker above to use date input feature detection. The problem is: the server side is set up to receive the date in "yyyy-mm-dd" format (which is the only possible date format that can be POST'ed if the input type is "date", i.e. on mobile). Browsers that support date inputs automatically display the in a more human readable "dd/mm/yyyy" (for UK locales). If we dynamically change the input type to text then we'd either have to accept the side effect of the date appearing as yyyy-mm-dd to the user, do something on the server side to accept both formats or do something with an extra hidden input or something, none of which sound great...

@CHTJonas appreciated if you could confirm this is still doing something vaguely sensible on Safari before we next tag a release!

**Comment by CHTJonas** [comment] 2018-08-18 22:46
Yep all working on desktop Safari/macOS! Good work guys! 🎉

**Comment by GKFX** [comment] 2018-09-26 13:41
Sentry issue possibly relevant: [CAMDRAM-WEB-J](https://sentry.io/camdram-webteam/camdram-web/issues/701868787/).

**Comment by GKFX** [comment] 2019-03-16 00:09
Closing in favour of #612.

**Closed by GKFX** 2019-03-16 00:09 UTC
Labels: bug, design, regression
