### ISSUE TITLE
Empty item in search results

### ISSUE THREAD

**Issue by dtwood** [camdram/camdram#335] opened 2015-10-17 15:32 UTC
There's an empty item in the search results for pirates at http://www.camdram.net/search?q=pirates.

**Comment by ajf58** [comment] 2016-05-05 22:14
I can't reproduce this, so I'm closing it for now. We can reopen if someone else is able to duplicate the issue.

**Comment by dtwood** [comment] 2016-05-06 12:09
It now appears for me as the fourth item in that search result

**Comment by philosophicles** [comment] 2016-05-06 12:45
I can reproduce this. To be clear, this is the actual search results **page** not the auto-complete drop down list as you type 'Pirates'.

![pirates](https://cloud.githubusercontent.com/assets/5232616/15073288/acfecbb6-1390-11e6-86fe-0660de8f7ff0.PNG)

**Comment by philosophicles** [comment] 2016-05-06 12:50
Have looked at our show table in SQL; a brief query using 

    WHERE `description` LIKE '%pirates%'
    ORDER BY `start_at` DESC 

suggests this may not be an actual row of data in SQL causing this empty item, as nothing is returned between the G&S pirates (listed above in search results) and the COGGLES show (listed below).

**Comment by CHTJonas** [comment] 2018-06-14 13:51
Fast forward two and a bit years.....

This seems to no longer be an issue. I'm not sure if it's because the bug has been fixed, the SQL record removed or just that new shows have been added in the meantime and searches are limited to a certain max number of results. Anyone still able to reproduce this?

**Comment by philosophicles** [comment] 2018-06-16 04:21
I no longer see it in that particular search results page either. See no reason not to close this until somebody sees it again, if ever.

**Closed by philosophicles** 2018-06-16 04:21 UTC
Labels: task
