### ISSUE TITLE
Date overflow in search results

### ISSUE THREAD

**Issue by dtwood** [camdram/camdram#239] opened 2014-11-10 00:46 UTC
Another search index related issue from me (it's almost as though I don't have access to any of the editing stuff :-P) - searching for "the week in cambridge" shows the show as being in Feb 2106 (the overflow time of a 32bit unix date), despite the show page showing the year -0001 (which I also don't think is a year - no idea what they did to get this in the database).

The same show also manages to crash the sign-in sheet generator, although I highly doubt that it's the crash you were looking for.

**Comment by CHTJonas** [comment] 2018-07-10 02:05
I have no idea how this was possible but the `start_at` and `end_at` fields were both set to `0000-00-00 00:00:00` in the DB! The exact error was
```
[2018-07-10 02:58:23] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "start_date": datefmt_format: string '' is not numeric, which would be required for it to be a valid date: U_ILLEGAL_ARGUMENT_ERROR" at /var/www/camdram/20180704/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 1159 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"start_date\": datefmt_format: string '' is not numeric, which would be required for it to be a valid date: U_ILLEGAL_ARGUMENT_ERROR at /var/www/camdram/20180704/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:1159, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): datefmt_format: string '' is not numeric, which would be required for it to be a valid date: U_ILLEGAL_ARGUMENT_ERROR at /var/www/camdram/20180704/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToLocalizedStringTransformer.php:92)"} []
```

Now I tried a manual correction and spent about two hours on this but couldn't get it to work. @hoyes can you see what the fishy business is here? Link: https://www.camdram.net/shows/2012-the-week-in-cambridge

**Comment by philosophicles** [comment] 2018-07-16 00:04
@CHTJonas got curious and took a quick look. This show was using the "multi-venue" option (until now, the front-end showed two different date ranges, both "weird" and both referencing the same venue, but referenced twice). 

So, that meant it had a row in `acts_performances` (only one though...?) which was driving the dates shown in the front end, rather than the `start_at`, `end_at` fields (which I saw you had updated). The dates in `acts_performances` were also all `0000-00-00 00:00:00`. I manually updated them in phpMyAdmin and we seem to be all good now. 

Interestingly even after playing around with this show's settings via the front-end some more, `start_at` and `end_at` didn't seem to have updated. I see all recent shows seem to have time of midnight for these fields so I think maybe they're not actually being used in the way you (and I) thought they were: possibly `acts_performances` is the only place that really matters for front-end presentation of when a show is happening?

**Comment by philosophicles** [comment] 2018-07-16 00:06
Aha, yes, @CHTJonas see #386 - `start_at` and `end_at` are indeed not first-class citizens in our date-logic.

**Comment by philosophicles** [comment] 2018-07-16 00:06
So basically, any problem with show dates => fix data in `acts_performances`.

**Comment by philosophicles** [comment] 2018-07-16 00:07
Given this seems to have been a totally one-off occurrence I don't think there's any deeper task here to find the root cause and fix it. Closing as done, assuming nobody disagrees.

**Closed by philosophicles** 2018-07-16 00:07 UTC

**Comment by hoyes** [comment] 2018-07-16 00:09
Agree yes - the "real" fix here is #386. (sorry I missed your comment last week @CHTJonas)

**Comment by CHTJonas** [comment] 2018-07-17 11:59
No worries. @philosophicles I should add that the date I chose was completely made up so I have no idea what the right one should be...

**Comment by philosophicles** [comment] 2018-07-18 05:54
Thankfully that show happened to have written their relevant dates in the description!
