### ISSUE TITLE
Support emails generated with wrong subdomain

### ISSUE THREAD

**Issue by CHTJonas** [camdram/camdram#401] opened 2018-06-14 23:37 UTC
Emails to websupport@ result in an email being generated such as:
```To investigate, visit https://old.camdram.net/administration/support?viewissue=xxxxx```

We should update this from old. to www.camdram.net.

**Comment by hoyes** [comment] 2018-06-14 23:43
This is effectively a duplicate of  #263. Support e-mails are still being handled by a v1 checkout on Antigone, hence the URL. I wrote an e-mail handler in v2 a while back, which needs testing and integrating at some point after e-mail handling is moved over to Tiberius...

Could do a local modification in the v1 checkout on Antigone to fix this in the short term.

**Closed** 2018-06-14 23:47 UTC
