### ISSUE TITLE
Broken link template for society applications

### ISSUE THREAD

**Issue by philosophicles** [camdram/camdram#358] opened 2016-02-16 13:47 UTC
When a society is advertising for applications to direct/produce, the society's page on Camdram has a 'Get involved' box for this, with a 'More details' link.

The link goes to https://www.camdram.net/vacancies/applications/society-slug.
It should go to https://www.camdram.net/vacancies/applications#society-slug.

Minor differences :)

**Comment by philosophicles** [comment] 2016-02-16 13:57
Thought I might be able to fix this really simply in my lunchbreak; I'm sure it is pretty simple, but I don't know the code base well enough to go direct to the right place. (Guessing this is in routing somewhere?)

**Comment by ajf58** [comment] 2016-02-17 20:27
I think the issue is down to how getAction has been implemented in [camdram/src/Acts/CamdramBundle/Controller/ApplicationController.php](https://github.com/camdram/camdram/blob/2277e5df048d39848a33f1832dede9bdafb8d083/src/Acts/CamdramBundle/Controller/ApplicationController.php). Specifically, there is an assumption that applications are only linked to shows, whereas in this case it's linked to a society. I think there's just an additional ```else if``` clause required. 

That said, I'm not sure how this method handles either shows or societies well in the case where there are multiple adverts listed. I think it would be better to change the id tags in the template to use the advert's primary key as the id, and then both this lookup and the precision of the result is better, at the cost of losing more friendly looking links.

**Comment by philosophicles** [comment] 2016-09-24 09:59
I've revisited this as another user has encountered the same problem. 

Looking at `getAction()`, and examining the current site behaviour, my interpretation is that the problem is with how `$application` is set (l34) rather than the `if` clause starting on l36. 

I think `$application` is failing to get set correctly for these society applications, so we'd want to address that before starting the `if` clause surely, by extending how `$application` is set. 

However, I'm still drawing a blank on what precisely within l34 is falling down for societies but not shows. I just don't know the behaviour of the constituent methods and afraid I don't have time to dig into it. I wanted to write this thought down in case it helps anyone else move forwards!

**Comment by hoyes** [comment] 2018-02-11 02:00
Should have tagged ae8b6b91360419e65352646c5b08485d12153baf with this ticket
Fixed in release 20180211

**Closed by hoyes** 2018-02-11 02:00 UTC
Labels: bug
