### ISSUE TITLE
Issue uploading image

### ISSUE THREAD

**Issue by stumo** [camdram/camdram#211] opened 2014-10-09 00:58 UTC
I have been trying to upload an image to http://www.camdram.net/shows/cast-2009-two-gentlemen-of-verona - each time the first time I try to upload an image it gives "HTTP 500 error" (behind when the image is uploading) - then the 2nd and subsequent times it appears to complete but with a broken image link. Deleting the image and re uploading gives the 500 error.

The image I'm trying to upload is attached (I tried with others as well)
![casttwogents](https://cloud.githubusercontent.com/assets/1047730/4569723/52d046c6-4f4f-11e4-85f1-1277e4878c6a.png)

**Comment by hoyes** [comment] 2015-01-03 16:44
Done any work on this @ajf58 ? Thinking of taking a look

**Comment by ajf58** [comment] 2015-01-03 20:33
The only other thing I've tried is using a JPEG version, which also didn't work. At the time I was able to reproduce the issue on my working copy of the site, but I've not re-tried it since I removed the in-progress tag. If you want to reassign this to yourself and mark it as in progress please do.

**Comment by hoyes** [comment] 2015-01-25 18:15
Just to say I have almost completed rewriting symfony2-image-manager bundle, but haven't checked it in yet. I can't remember the exact error off-hand but the fundamental problem was that it was doing zero validation of the uploaded image! Upcoming code should make it more robust.

**Comment by hoyes** [comment] 2015-12-27 22:28
To be honest I've lost my WIP on this, and it would have likely become tricky to merge by now anyway so we're back to square one on this.

**Comment by hoyes** [comment] 2018-01-21 21:35
I recently overhauled this, replacing the custom image manager bundle with https://github.com/1up-lab/OneupUploaderBundle.
Still to do:
 - [ ] venue image uploads
 - [ ] society image uploads

**Comment by philosophicles** [comment] 2018-06-10 18:43
@hoyes Is there a way that Camdram admins can replace a society's image without the normal upload interface existing? E.g. if I were to manually hash the image file with the right algorithm and paste it in via phpmyadmin? Or is that way too cowboy to be worth trying? 

We have this as a request in ticket 78086.

**Comment by GKFX** [comment] 2018-06-14 08:41
I've created a workaround; upload images to https://www.camdram.net/shows/2000-test-show. Then read off the image ID from the shows table, and transfer it to the society's database entry. Let me know if this is going to cause any issues; it's worked for the Dryden society.
@hoyes I've assigned a support ticket to myself that was assigned to you related to this issue.

**Comment by CHTJonas** [comment] 2018-06-14 13:13
So the images themselves are stored in `/var/www/camdram/shared/data` with their MD5 hashes being the filenames (although interestingly I tried hashing a few files in that directory with `md5sum` and the hash didn't match the filename). Another workaround would be to manually SFTP them into production and then add a corresponding entry in the `acts.images` table, linking this into the society too.

**Comment by hoyes** [comment] 2018-06-14 13:41
The filenames are sort of meaningless really so long as it matches the row in the acts_images table. Not sure why I chose md5() in hindsight.

I'll finish this off at the weekend....kept putting it off... It just requires copy+pasting the relevant bits from Shows to Societies/Venues.

**Comment by hoyes** [comment] 2018-06-16 16:09
This should now be fixed for societies and venues.

**Closed by hoyes** 2018-06-16 16:09 UTC
Labels: bug, in-progress
