### ISSUE TITLE
Reject Assignment doesn't do anything on v2

### ISSUE THREAD

**Issue by dstansby** [camdram/camdram#264] opened 2015-01-02 16:07 UTC
In the Issues section of the website, pressing "Reject Assignment" doesn't seem to do anything.

**Comment by dstansby** [comment] 2015-01-02 16:14
The problem I assume is that in V2 it doesn't actually let you reject an assignment unless it's assigned to you - either there should be V1 behavior (anyone can reject and assignment, which seems sensible to me), or the reject assignment button shouldn't exist unless the issue is assigned to yourself.

**Comment by dstansby** [comment] 2015-01-02 17:19
Fixed in https://github.com/dstansby/camdram/commit/4f75911b89e3d0078370e3462be540aa573e040e , assuming anyone rejecting assignments is what we want.

(I'm having fun trying to work out how to do all this branching stuff at the moment, so apologies if it's a bit of a mess0

**Comment by hoyes** [comment] 2015-01-02 17:51
Cheers David - agree with the problem and the fix.

I've merged this in direct from your feature branch. Hopefully this will help your branching issues as your repo should now be in sync with Camdram's!

**Comment by ajf58** [comment] 2015-01-02 20:09
I'm not sure I understand either the issue that's been raised or the resolution. Let's start at the beginning with the very broad statement. "Reject Assignment doesn't do anything on v2"

On V2 live site and my local copy of Camdram without this change:
1. I viewed [issue 75075](https://www.camdram.net/admin/issues/75075), which is an open issue currently assigned to me.
2. Clicking on "Reject Assignment" causes the issue to be unassigned. This is verified by being able to assign this issue to myself again, and/or returning to the issue listing and seeing the issue appear under the unassigned issue list.
3. I performed the same process from the issue summary page and got the same behaviour.
Reject assignment does work exactly as intended in this situation.

The specific bug raised is related to rejecting assignment of issues that aren't assigned to the logged in user. It's quite boring trying to duplicate an issue with such a broad title. 

It looks like a good fix for allowing users to reject assignments held by other users, but now the comment immediately above the conditional statement doesn't match the code itself, which is really annoying. Please can you update it so that the two are in sync?

**Comment by dstansby** [comment] 2015-01-02 20:44
Sorry, I'm currently trying to have a go at actually fixing stuff myself in an attempt to help, and since I'm new to a. Camdram code and b. Git I'm probably not doing stuff properly so please do point out politely where I'm going wrong if I am!

The original bug report is accurate to what I thought was the bug - I didn't have any issues assigned to me on Camdram so I thought that it was generically not working.

**Comment by hoyes** [comment] 2015-01-02 21:04
Many thanks for your efforts fixing this @dstansby . I agree with @ajf58 that it's helpful to modify the issue title if the scope changes, even though the exact nature of the problem was evident from your later comments.

As it's a trivial change, I've just updated the comment to save a pull request / merge cycle. I think this is now fixed too, so closing.

**Closed by hoyes** 2015-01-02 21:04 UTC
