### ISSUE TITLE
Can't add new venue admins who don't yet have an account

### ISSUE THREAD

**Issue by GKFX** [camdram/camdram#610] opened 2019-03-07 10:04 UTC
Adding a new admin who doesn't have an account to a venue results in nothing happening, i.e. the user doesn't see an error and no `PendingAccess` entity appears to be created.

**Comment by CHTJonas** [comment] 2019-03-11 09:21
Duplicate of #461 I think

**Closed** 2019-03-11 09:21 UTC
Labels: bug, duplicate
