### ISSUE TITLE
Add A Search By Role Feature

### ISSUE THREAD

**Issue by evalemmy** [camdram/camdram#2069] opened 2023-02-08 22:19 UTC
@CHTJonas 

We would like to add a search by role feature to enable TD's and Producers to find techies either in a role of view a list of most recent people to have undertaken that role

We believe adding a drop-down menu option to the prod role tab of each show admin would help standardise the spelling of key roles such as Set Designer Lighting Designer PLX

It would be extremely valuable

**Comment by hoyes** [comment] 2023-02-09 10:22
Hi @evalemmy, this is technically a duplicate of #55 (which was closed in 2014 but could be reopened) so linking here to at least avoid repeating the same arguments.

**Comment by evalemmy** [comment] 2023-02-09 10:50
Hi there I have read thread #55 and also thread #22  - it seems a consensus was reached about adding a checklist where people could select roles they were interested in and then you could search by the checklist?

Can I ask why this never actually went ahead?

**Comment by hoyes** [comment] 2023-02-10 08:28
Probably a lack of time or inclination :)

I worry a little that #22 may still undermine the vacancies system and open applications if only used to create a private messaging system. I would suggest that users' role preferences are initially used to personalise the vacancies page.

Having said that, if someone has time to implement a different version of #22 I won't object (I don't do much theatre these days).

**Comment by CHTJonas** [comment] 2023-03-02 18:58
_/me dons impartial Camdram Web Team super admin hat_

We've discussed this internally a bit via private email and there is still no clear consensus on the work that would need to be done to implement this. There are some of us in favour, others against and others somewhat on the fence, but moreover no one has volunteered to do what in my opinion would be the significant software development work required to get this off the ground.

The issues of 'not enough techies' or 'no suitable applicants' is unfortunately not new and discussion on adding a 'search by role' feature has been hashed out _ad infinitum_ several times already. This is fundamentally a community social problem and one that is not ideally addressed with a technological solution.

That being said, if someone (a third party) is willing to put the effort in do the coding for this, then I would suggest we evaluate their particular implementation and give feedback on it, with a few to inclusion if possible. As it is, I think most of the Camdram Web Team have neither the free time nor the inclination to do this themselves.

---

A drop-down menu option when entering a role sounds like an excellent idea and can be addressed in #2089.

**Closed** 2023-10-02 16:04 UTC
Labels: duplicate, enhancement, discussion needed, help wanted
